HelloWorldMVC/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace HelloWorldMVC.Models
{
    public class Student
    {
        [Required]// makes sure there is something there.
        [RegularExpression(@"^\d{9}$", ErrorMessage = "SID must be 9 digits")]
        public string StudentId { get; set; }

        [Required(ErrorMessage = "Give me your name")]// makes sure there is something there.
        [Display(Name ="First Name ")]
        [StringLength(25, ErrorMessage = "This must be 1 to 25 characters")]
        public string FirstName { get; set; }
        
        [Required]// makes sure there is something there.
        [Display(Name = "Last Name ")]
        public string LastName { get; set; }

        // value types such as DateOfBirth are always required because they have to have a value.
        public DateTime DateOfBirth { get; set; }

        //Note: we are not implementing this but this will validate 
        //an email to the fullest.
        [EmailAddress]
        public string EmailAddress { get; set; }



    }
}

HelloWorldMVC/Models/StudentDB.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace HelloWorldMVC.Models
{
    public static class StudentDB
    {
        public static bool AddStudent(Student s)
        {
            //TODO: Add database code here...

            //return true to pretend insert was successful.
            return true;
        }
    }
}

HelloWorldMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelloWorldMVC.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            DayOfWeek day = DateTime.Today.DayOfWeek;
            if(day == DayOfWeek.Thursday)
            {
                //ViewBag is a wrapper around ViewData
                ViewBag.Message = "It's Thorsday!";
                //Same as above
                ViewData["Message"] = "It's Thorsday!";

                //Data Inside of ViewBag/ViewData is automatically sent to the view.
            }
            else
            {
                ViewBag.Message = "Hulk Smash!";
            }
            return View();
        }

        public ActionResult Contact()
        {
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
        public void Casey()
        {
            Response.Write("It's break time joe!");
        }
        
    }
}

HelloWorldMVC/Controllers/StudentController.cs
using HelloWorldMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelloWorldMVC.Controllers
{
    public class StudentController : Controller
    {
        //When the user navigates to a url (HttpGet)
        //When Student/Index is found in the route          // the form default submits to a post with the same name
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        
        //HttpPost  // This will get called after a user submits a HttpForm
        [HttpPost]
        public ActionResult Index(FormCollection data)
        {
            //Validate all form data

            //encapsulate form data in an object   
            Student stu = new Student
            {
                StudentId = data["txtSID"],
                FirstName = data["txtFName"],
                LastName = data["txtLName"],
                DateOfBirth = Convert.ToDateTime(data["txtDOB"])
            };
            //if everything is valid, add to database
            if (StudentDB.AddStudent(stu))
            {
                //ViewBag data only works for the current request
                ViewBag.StudentAdded = true;
            }
            //let the user know it was successful
            //Or display error messages

            return View();
        }
    }
}

HelloWorldMVC/Controllers/StudentModelBindingController.cs
using HelloWorldMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HelloWorldMVC.Controllers
{
    public class StudentModelBindingController : Controller
    {
        // GET: StudentModelBinding/Create
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Models.Student stu)
        {
            //this ensures all validation rules for the model have passed.
            if (ModelState.IsValid)
            {
                if (StudentDB.AddStudent(stu))
                {
                    ViewBag.Added = true;
                }
            }

            return View();
        }
    }
}

HelloWorldMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About Casey's Company";
}

<h2>About</h2>

<p>
    This is example text to visually test my site. helodsoa hke ls ha lhaf asd  hsdkkkshfsdkh hia od;a hadsfa
    dfkhsklgal la l l ll lhskagha
</p>

HelloWorldMVC/Views/Home/Contact.cshtml
@{ 
    ViewBag.Title = "Contact Us";
}

    <header>
       <h1>Contact Information Is Below</h1>
    </header>
    
    <a href="~/Views/Home/Index.cshtml">content</a>
    <!--Non working link 
        Do Not Point Directly to a View-->
    <br />

    <a href="~/Home/index">Go To Index</a>

    <br />
    <br />
    @**DONT PUT CONTROLLER AFTER CONTROLLER NAME*@
    @Html.ActionLink("Go to Index!", "Index", "Home");

    


    <address>
        4500 Steilacoom Blvd SW
        Lakewood WA 98499
    </address>

HelloWorldMVC/Views/Home/Index.cshtml
@{ 
    ViewBag.Title = "Home";
}

<h1>Welcome to the Home Page</h1>
@*if You dont use the bottom overload it will assume you are looking for a view in the current controller.*@
@Html.ActionLink("Contacts", "Contact");

@Html.ActionLink("Contact", "Contact", "Home");

<h2>@ViewBag.Message</h2>

<ul>
    @for (int i = 1; i <= 1000; i++)
    {
        <li>Product #@i</li>
    }
</ul>

HelloWorldMVC/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/css/DefaultStyle.css" />
</head>
<body>
    <h1>@ViewBag.Title</h1>

    <nav>
        <ul>
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("Contacts", "Contact", "Home")</li>
            <li>@Html.ActionLink("About Us", "About", "Home")</li>
            <li>@Html.ActionLink("Student", "Index", "Student")</li>
            <li>@Html.ActionLink("Add Student ModelBinding", "Create", "StudentModelBinding")</li>
        </ul>
    </nav>

    <main>
        @RenderBody()
    </main>
</body>
</html>

HelloWorldMVC/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Create Student";
}

<h2>Add a student</h2>

@if (ViewBag.StudentAdded != null && ViewBag.StudentAdded)
{
    <h3>Student added Succesfully!</h3>
}
else
{
<form method="post">

    <label for="txtSID">Student ID:</label>
    <input type="text" name="txtSID" />
    <br />
    <br />

    <label for="txtFName">First Name</label>
    <input type="text" name="txtFName" />
    <br />
    <br />

    <label for="txtLName">Last Name</label>
    <input type="text" name="txtLName" />
    <br />
    <br />

    <label for="txtDOB">Date of Birth</label>
    <input type="text" name="txtDOB" />
    <br />
    <br />  


    <input type="submit" value="Add Student"/>
</form>
}

HelloWorldMVC/Views/StudentModelBinding/Create.cshtml
@model HelloWorldMVC.Models.Student

@{
    ViewBag.Title = "Create Student";
}
@*the model @ model above means this page is binding to the Student class *@
<h2>Create</h2>

@if (ViewBag.Added == true)
{
    <h3>Student was added!</h3>
}

@*this is the same as the form tags*@
@*posts to the same url (same controller/ same action unless you specify the action/url*@
@using (Html.BeginForm())
{
    //form lable model binding
    @Html.LabelFor(m => m.StudentId)
    @Html.TextBoxFor(m => m.StudentId)
    @Html.ValidationMessageFor(m => m.StudentId)
    <br />
    @Html.LabelFor(m => m.FirstName)
    @Html.TextBoxFor(m => m.FirstName)
    @Html.ValidationMessageFor(m => m.FirstName)
    <br />
    @Html.LabelFor(m => m.LastName)
    @Html.TextBoxFor(m => m.LastName)
    @Html.ValidationMessageFor(m => m.LastName)
    <br />
    @Html.LabelFor(m => m.DateOfBirth)
    @Html.TextBoxFor(m => m.DateOfBirth)
    @Html.ValidationMessageFor(m => m.DateOfBirth)
    <br />
    <input type="submit" value="Create Student" />




}